eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false # eureka do not have to register its self
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
server:
  port: 8761
spring:
  application:
    name: discovery